services:
  docling-inference:
    image: ghcr.io/aidotse/docling-inference:dev
    ports:
      - 8080:8080
    environment:
      - DEV_MODE=1
      - AUTH_TOKEN=dev-key
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src:ro
      - hf_cache:/root/.cache/huggingface
      - ocr_cache:/root/.EasyOCR
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  hf_cache:
  ocr_cache:
