services:
  docling-inference:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DEV_MODE=1
    volumes:
      - ./logs:/logs
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  hf_cache:
